# Generated by Django 5.0 on 2023-12-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangomodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelodos',
            table='relaciones',
        ),
        migrations.AlterModelTable(
            name='modelotres',
            table='detalles',
        ),
        migrations.AlterModelTable(
            name='modelouno',
            table='usuarios',
        ),
    ]
