# Generated by Django 5.0 on 2023-12-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangomodel', '0003_cliente_producto_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelodos',
            name='modelo_tres',
        ),
        migrations.RemoveField(
            model_name='modelodos',
            name='modelo_uno',
        ),
        migrations.DeleteModel(
            name='ModeloTres',
        ),
        migrations.DeleteModel(
            name='ModeloDos',
        ),
        migrations.DeleteModel(
            name='ModeloUno',
        ),
    ]
