# Generated by Django 5.0 on 2023-12-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangomodel', '0004_remove_modelodos_modelo_tres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
