# Generated by Django 5.0 on 2023-12-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangomodel', '0005_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='En Proceso', max_length=100),
            preserve_default=False,
        ),
    ]
